### ISSUE TITLE
Not very responsive to wide

### ISSUE THREAD

**Issue by kescobo** [tlienart/ft-academic-resume#4]
And it's compressing some stuff

![image](https://user-images.githubusercontent.com/3502975/130648162-370fb7ce-7c30-48f9-a37d-58ad9d537170.png)

PS - I'm just testing out this template, and it's in great shape! I thought I'd use issues to keep track of stuff as I see it, but I don't want to pester. Let me know if you'd prefer I just take notes and convert this to a single mega issue :-)

**Comment by tlienart** [comment]
No I think this is nice, ideally if you could also link to a draft repo where we could try playing around with the CSS so that we find a good way to fix this, that would be great :)

**Comment by kescobo** [comment]
It's the `main` branch of my fork [here](https://github.com/kescobo/ft-academic-resume/tree/main)

**Comment by tlienart** [comment]
can you make this a full repo (not a branch) + give me access to make iterations on it easier?

**Comment by kescobo** [comment]
:+1: https://github.com/kescobo/FranklinAcademic

**Comment by tlienart** [comment]
ah right, you need to mimic the exact syntax from `index.md` including the commands like `\begin{section}...` etc, otherwise things are not wrapped in the proper bootstrap elements and won't be correct.

If you use the syntax demonstrated in `index.md` things will be responsive as expected.

**Comment by kescobo** [comment]
Alright, I changed the content of `reserach/index.md` to

```
@def title = "Research"

\begin{section}{name="Research", class="wg-pages"}

@@col-12,col-lg-12

## Human microbiome and child development

Here's some content

@@

\end{section}
```

Which is much improved: 
![image](https://user-images.githubusercontent.com/3502975/131172489-a6558d74-fa6c-4a49-a0bc-a3019f012013.png)

But it's still not taking up a lot of the horizontal space. There seems to be a `max-width` parameter that can be tweaked (the header for blog posts is set to 2000 for example). Using developer tools, I found that I could change the parameter `article-container{max-width` to a different value (it's currently set at 760, which seems crazy small. I set it to 1200, and it suits me much better. 

Not sure it makes sense to change the default CSS, but I'm working on a function to allow something like blog posts to go under research - let me know if you'd like that to be a PR. Otherwise, fine with me to close this issue

**Comment by tlienart** [comment]
this is just to list the content right? feel free to tweak this on your side but here I'm following the academic template's geometry and won't touch this; I suspect they did it this way so that the look and feel on mobile is similar

**Comment by kescobo** [comment]
> feel free to tweak this on your side but here I'm following the academic template's geometry and won't touch this;

Yeah, totally makes sense. I'm mostly just documenting I'm case someone else has similar needs (including myself, when I inevitably forget about how I solved it 😛)

> I suspect they did it this way so that the look and feel on mobile is similar

Not sure about this, on mobile the headers stack

![Screenshot_20210829-205834.png](https://user-images.githubusercontent.com/3502975/131271697-36bf283f-54b7-424d-b931-551b0d4262ef.png)

But in any case, I agree that it makes the most sense to stick to the baseline template 👍

**Comment by tlienart** [comment]
It's very difficult to maintain a template that is responsive and looks good, near impossible actually (unless that's your main project) So I'm generally on the side of "provide a decent base and let users do their own tweaks", as for ones own website, the work doesn't seem as thankless anymore 😅

I think here the kind of stuff I'd be ready to add are blatant big problems, but the rest is too much subject to each's taste :)
