### ISSUE TITLE
Lines connecting multiple "experience" blocks

### ISSUE THREAD

**Issue by kescobo** [tlienart/ft-academic-resume#6]
**franklin:**

![image](https://user-images.githubusercontent.com/3502975/139699928-5f5b9238-6d8f-4b49-a422-8c8fbb64fe87.png)

**academic:**

![image](https://user-images.githubusercontent.com/3502975/139700010-cf5bc815-50f7-4ca4-a70b-e998d90b8acb.png)

I guess it would require some kind of logic to figure out if it's the last item or not?

**Comment by tlienart** [comment]
nice yes, the logic for this is https://github.com/tlienart/ft-academic-resume/blob/74b0c6b996e7b35761edfb46ef10167dbe189827/utils.jl#L117-L163 I'm going to read through it now to see if I spot anything but might not have a lot of time (baby about to wake up 😅 ; so just in case I don't answer further that's where we have to look into to figure this out. Shouldn't be very hard though maybe a bit finicky 

oh and could you show the code you used for the screenshot? did you specify the `first` or the `active` argument?

**Comment by kescobo** [comment]
>oh and could you show the code you used for the screenshot? did you specify the first or the active argument?

[Here](https://github.com/kescobo/FranklinAcademic/blob/main/index.md?plain=1#L70-L146) - I used `active=true`

**Comment by kescobo** [comment]
So it looks like the easiest thing would be to add a `last` argument, then it's something like

```
if first && last
    line = vspace * pill * vspace
elseif first
    line = vspace * pill * vbar
elseif last
    line = vbar * pill * vspace
else
    line = vbar * pill * vbar
end
```

There may be some more concise logic...

**Comment by kescobo** [comment]
This works:

https://github.com/kescobo/FranklinAcademic/blob/main/utils.jl#L117-L157

EDIT: this is outdated - was originally [pointing here](https://github.com/kescobo/FranklinAcademic/commit/1e20e89c60cb7f473c96da2ac478afd9d8b91721#diff-a48746cae70c44e7e105b594aad338ddd105c93c1cb445a40ba6aab785ba69e5)

**Comment by kescobo** [comment]
Oh, actually this is much nicer:

```
    line = pill
    line *= last ? vspace : vbar
    line = (first ? vspace : vbar) * line    
```

**Comment by kescobo** [comment]
Even cleaner now https://github.com/kescobo/FranklinAcademic/blob/main/utils.jl#L144
